@startuml
class DeviceSorter {
    - <<const>> DEFAULT_SPLIT : int = 3
    + DeviceSorter(console:IConsole)
    + set_parser(parser:ICommandLineParser) : void
    + sort() : void
}
IDeviceSorter <|-- DeviceSorter
DeviceSorter --> "_parser" ICommandLineParser
DeviceSorter --> "_Console" IConsole
@enduml
